### ISSUE TITLE
Custom validations can not be called twice

### ISSUE THREAD

**Issue by pietere** [pluginaweek/state_machine#151] opened 2012-01-02 14:13 UTC
I have a state machine like this

```
  state_machine :publication_state, :initial => :draft do
    event :submit do 
      transition :draft => :submitted
    end
    event :refuse do
      transition :submitted => :draft
    end
    event :accept do
      transition :submitted => :published
    end
    state :submitted do
      validate :validate_something_fancy
    end  
    state :published do
      validate :validate_something_fancy
    end    
  end
```

and then 

```
def validate_something_fancy
   ...
end
```

The problem is that I can not reuse the validation method "validate_something_fancy" 2 times. It only works 1 time.

**Comment by obrie** [comment] 2012-01-02 15:25
This is a dupe of #103.  See the "Validations" heading here: http://rubydoc.info/github/pluginaweek/state_machine/master/StateMachine/Integrations/ActiveRecord

**Closed as completed by obrie** 2012-01-02 15:25 UTC

**Comment by pietere** [comment] 2012-01-02 15:28
oops...didn't see that. Thanks!
