### ISSUE TITLE
on: any don't fire the callback

### ISSUE THREAD

**Issue by ulisses-almeida-mowa** [pluginaweek/state_machine#213] opened 2012-10-25 21:56 UTC
For example

``` ruby
transition underway: :completed, on: :arrive
after_transition on:  any, do: :some_thing
```

but if I try

``` ruby
transition underway: :completed, on: :arrive
after_transition underway:  any, do: :some_thing
```

Works. Why any for events don't work, or I miss something?

activerecord (3.2.6)
state_machine (1.1.2)

**Comment by the8472** [comment] 2012-11-26 10:24
`any` is a StateMatcher, it doesn't match events. So just omit the `:on` if you don't want to restrict it to specific events.

**Comment by obrie** [comment] 2013-02-18 14:36
This is a dupe of #190 and has since been supported via 0f6dff1e5c65649ea9b470f61c89ecdb0a6e2037 -- thanks for reporting the issue!

**Closed as completed by obrie** 2013-02-18 14:36 UTC

**Comment by ulissesalmeida** [comment] 2013-02-18 14:52
Thanks!
