### ISSUE TITLE
Mongoid 2.3.0 :initial fails

### ISSUE THREAD

**Issue by nofxx** [pluginaweek/state_machine#127] opened 2011-10-04 10:13 UTC
It's time for @durran `s:

https://github.com/durran/state_machine/commit/3f3829b79ce29183d1a64a21c10c08021a3f3958

Thanks all.

**Comment by abhishiv** [comment] 2011-10-30 16:29
Can this be pulled in please?

**Comment by obrie** [comment] 2011-10-30 16:41
Hey guys -

This is a dupe of #125.  I mentioned in that pull request that it's on my radar.  I'm sorry it's taking me so long.  Trust me, it'll be pulled in soon.

**Closed as completed by obrie** 2011-10-30 16:41 UTC

**Comment by abhishiv** [comment] 2011-10-30 18:26
Thanks. 

And thanks for your effort guys. This is absolutely the best state_machine implementation I have seen for ruby :)
